# 单个eureka服务中心
spring:
  application:
    name: eureka-server

# 服务器配置
server:
  # 指定该Eureka实例的端口
  port: 8761
  
# eureka服务配置
eureka:
  instance:
    hostname: eureka-server
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/



